import { ArrowLeft, Check, MessageCircle, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import { Share2 } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import ArticleRating from "@/components/ArticleRating";

export const articleEntries = [
  { slug: "riyadh-home-cleaning", title: "تنظيف الرياض: خطوات البداية", intro: "طريقة عملية لترتيب طلب تنظيف منزلي في الرياض، من قراءة المساحة حتى كتابة التفاصيل المهمة.", sections: [["ابدأ بالمساحات الأكثر استخدامًا", "حدّد الغرف التي تحتاج عناية أولًا: المطبخ، دورات المياه، أو مناطق الاستقبال. هذه البداية تساعد على توضيح الأولوية بدل وصف عام قد يضيع التفاصيل."], ["اكتب ما تريد بوضوح", "اذكر نوع المكان، عدد الغرف، وهل تحتاج تنظيفًا دوريًا أو عميقًا، ثم أضف أي نقطة خاصة مثل الزجاج أو الأفران أو آثار انتقال السكن."], ["ثبّت الوقت قبل اليوم", "اختر نافذة زمنية واقعية، وتأكد من سهولة دخول الفريق وموقف السيارة إن لزم. تنسيق هذه النقاط مبكرًا يجعل اليوم أخف." ]] },
  { slug: "kitchen-care", title: "العناية بالمطبخ دون إرهاق", intro: "خطوات صغيرة تجعل تنظيف المطبخ عادة ممكنة بدل أن تتحول إلى مهمة كبيرة في نهاية الأسبوع.", sections: [["قسّم العمل", "ابدأ بسطح واحد أو منطقة واحدة في كل مرة، مثل حوض الغسيل أو الموقد. التقسيم يقلل الإحساس بالفوضى ويمنحك نتيجة ظاهرة بسرعة."], ["اترك المنتج ليعمل", "بعد وضع المنظف المناسب للأسطح، اتركه لوقت قصير وفق تعليمات المنتج قبل المسح. تجنب خلط المواد، خصوصًا المواد القوية، واحرص على التهوية."], ["ضع ترتيبًا أسبوعيًا", "خصص وقتًا قصيرًا لمسح الأسطح والثلاجة وأماكن التخزين. الاستمرار الخفيف أسهل من انتظار تراكم يحتاج مجهودًا كبيرًا." ]] },
  { slug: "ac-maintenance", title: "متى تحتاج إلى صيانة التكييف؟", intro: "إشارات مبكرة تساعدك على طلب فحص التكييف قبل أن تصبح المشكلة أكبر في الأيام الحارة.", sections: [["ضعف الهواء أو التبريد", "إذا لاحظت فرقًا واضحًا في تدفق الهواء أو درجة التبريد، فهذه إشارة جيدة لطلب فحص مختص بدل الاستمرار في التشغيل بكفاءة أقل."], ["روائح أو أصوات غير معتادة", "ظهور رائحة غريبة أو صوت متكرر يستحق التحقق. لا تحاول فتح الأجزاء الداخلية بنفسك إذا لم تكن مختصًا."], ["الصيانة الوقائية", "الفحص الدوري قبل الذروة يساعد على ترتيب التنظيف والفلاتر ومعالجة الملاحظات الصغيرة مبكرًا." ]] },
  { slug: "furniture-moving", title: "نقل العفش بهدوء من باب إلى باب", intro: "أربع نقاط تسبق يوم النقل وتساعد على حماية القطع وتنظيم الوقت.", sections: [["اعرف القطع الحساسة", "حدّد المرايا والأجهزة والقطع الكبيرة أو القابلة للكسر. اذكرها عند الطلب حتى يكون التغليف والتعامل معها أوضح."], ["قياس المداخل والمصاعد", "تأكد من مسارات الخروج والدخول والمصعد ومواقف التحميل. هذه التفاصيل تحد من المفاجآت في يوم النقل."], ["جهز ما تحتاجه أولًا", "ضع الوثائق والأدوية والشواحن والاحتياجات اليومية في حقيبة منفصلة لا تدخل ضمن الصناديق." ]] },
  { slug: "jeddah-humidity-cleaning", title: "تنظيف جدة في الأجواء الرطبة", intro: "كيف تحافظ على إحساس المنزل المنعش حين تكون الرطوبة جزءًا من اليوم.", sections: [["التهوية أولًا", "جدد الهواء عند ملاءمة الطقس، وركز على الأماكن المغلقة مثل الحمامات والمطبخ. التهوية المنتظمة تقلل بقاء الروائح والرطوبة."], ["تجفيف الأسطح", "لا تترك المناشف أو الأسطح المبللة لفترة طويلة. التجفيف البسيط بعد الاستخدام جزء مهم من العناية اليومية."], ["راقب الزوايا", "افحص المناطق خلف الأجهزة وتحت الأحواض وحول النوافذ بانتظام، واطلب المعالجة عند ظهور مؤشرات تحتاج خبرة." ]] },
  { slug: "makkah-service-planning", title: "ترتيب موعد الخدمة في مكة", intro: "قائمة مختصرة للتواصل بوضوح عند طلب خدمة تنظيف أو صيانة أو نقل عفش في مكة.", sections: [["اكتب المدينة والحي", "ابدأ برسالة واضحة تذكر المدينة والحي ونوع المكان. هذا يسهّل تقدير التفاصيل وتنسيق الموعد."], ["اذكر الخدمة والموعد", "حدّد الخدمة المطلوبة ونافذة الوقت الأنسب لك. وإذا كانت لديك مرونة في الأيام، اذكرها في الرسالة."], ["أضف أي ملاحظة ضرورية", "مثل وجود مصعد أو قطع كبيرة أو منطقة تحتاج عناية إضافية. الملاحظات المبكرة تقلل الحاجة للتعديل لاحقًا." ]] },
] as const;

export default function ArticleDetailPage() {
  const [, params] = useRoute("/articles/:slug");
  const article = articleEntries.find((entry) => entry.slug === params?.slug);
  if (!article) return <SiteShell><main className="article-detail" dir="rtl"><div className="shell"><h1>المقال غير متاح</h1><Link href="/articles" className="button">العودة إلى المقالات <ArrowLeft size={16} /></Link></div></main></SiteShell>;
  const shareArticle = () => {
    const url = window.location.href;
    const shareData = { title: article.title, text: `مقال من الإشراقة: ${article.title}`, url };
    if (navigator.share) { void navigator.share(shareData).catch(() => undefined); return; }
    window.open(`https://wa.me/?text=${encodeURIComponent(`${shareData.text}\n${url}`)}`, "_blank", "noopener,noreferrer");
  };
  return <SiteShell><main className="article-detail" dir="rtl"><header className="article-hero"><div className="shell article-hero-copy"><Link href="/articles" className="back-link">كل المقالات <ArrowLeft size={15} /></Link><span className="eyebrow"><i /> دليل الإشراقة</span><h1>{article.title}</h1><p>{article.intro}</p></div></header><article className="section article-reading-section"><div className="shell article-prose">{article.sections.map(([heading, body], index) => <section className="article-reading-step" key={heading}><span>0{index + 1}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}<aside><Sparkles size={22} /><div><strong>هل تحتاج ترتيب الخطوة التالية؟</strong><p>يمكنك سؤال مساعد الإشراقة عن هذه المقالة أو فتح واتساب لشرح احتياجك.</p></div><Link href="/customer-service" className="text-link">اسأل المساعد <ArrowLeft size={15} /></Link></aside><div className="article-actions"><Link href="/booking" className="button">اطلب خدمة <ArrowLeft size={16} /></Link><a href="https://wa.me/966509614797" target="_blank" rel="noreferrer" className="button button-ghost"><MessageCircle size={17} /> واتساب</a><button className="button button-ghost" type="button" onClick={shareArticle}><Share2 size={16} /> مشاركة المقال</button></div><ArticleRating articleTitle={article.title} /></div></article></main></SiteShell>;
}
