// Design reminder: calm editorial service brand; preserve warm ivory space, deep teal actions, asymmetric sections, and gentle motion.
import { ArrowLeft, Check, Clock3, Droplets, Home as HomeIcon, MessageCircle, Phone, ShieldCheck, Sparkles, Truck, Wrench } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import VisitorFeedback from "@/components/VisitorFeedback";
import ServiceVideo from "@/components/ServiceVideo";

const assets = { hero: "/manus-storage/ishraqa-cleaning-caddy_6deee5d6.png", map: "/manus-storage/map-reference_99f2fe20.png", cleaning: "/manus-storage/cleaning-spark-transparent_91163e0d.png", maintenance: "/manus-storage/maintenance-tools-transparent_75e7c68e.png", moving: "/manus-storage/moving-box-transparent_9c5b10ea.png" };
const services = [
  { icon: HomeIcon, number: "01", title: "تنظيف المنازل", image: assets.cleaning, text: "تنظيف يومي وعميق للمنازل والشقق والمساحات التي تحتاج عناية منتظمة." },
  { icon: Wrench, number: "02", title: "الصيانة المنزلية", image: assets.maintenance, text: "تنسيق خدمات الصيانة الأساسية بوضوح، من التكييف إلى التفاصيل التي لا تحتمل التأجيل." },
  { icon: Truck, number: "03", title: "نقل العفش", image: assets.moving, text: "ترتيب ونقل الأثاث بعناية، مع تجهيز يناسب حجم المكان والموعد المطلوب." },
];
const cities = ["الرياض", "جدة", "مكة المكرمة", "المدينة المنورة", "الدمام", "الخبر", "الطائف", "أبها", "تبوك", "القصيم", "جازان", "مدن أخرى"];

function BookingCard() {
  const [step, setStep] = useState(1);
  const [data, setData] = useState({ city: "", cityDetail: "", service: "", serviceDetail: "", details: "", date: "", time: "", phone: "0509614797" });
  const update = (key: keyof typeof data, value: string) => setData((current) => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); const city = data.cityDetail.trim() || data.city || "لم يحدد"; const service = data.serviceDetail.trim() || data.service || "لم تحدد"; const message = encodeURIComponent(`السلام عليكم، أرغب في حجز خدمة من شركة الإشراقة.%0Aالمدينة أو الحي: ${city}%0Aالخدمة: ${service}%0Aالتاريخ: ${data.date || "مرن"}%0Aالوقت: ${data.time || "مرن"}%0Aتفاصيل إضافية: ${data.details || "لا توجد"}%0Aرقم التواصل: ${data.phone}`); window.open(`https://wa.me/966509614797?text=${message}`, "_blank", "noopener,noreferrer"); };
  return <div className="booking-card" id="booking"><div className="booking-intro"><span className="eyebrow">نموذج حجز مختصر</span><h2>اختر، أو اكتب ما تحتاجه بنفسك.</h2><p>أربع خطوات بسيطة تجهز لك رسالة واضحة على واتساب. لا يوجد دفع إلكتروني داخل هذه النسخة.</p><div className="stepper">{[1, 2, 3, 4].map((item) => <span key={item} className={item <= step ? "step active" : "step"}>{item.toString().padStart(2, "0")}</span>)}</div></div><form onSubmit={submit} className="booking-form">{step === 1 && <><label>اختر المدينة إن أردت<select value={data.city} onChange={(event) => update("city", event.target.value)}><option value="">اختر المدينة</option>{cities.map((city) => <option key={city}>{city}</option>)}</select></label><label>أو اكتب مدينتك أو الحي بنفسك<input value={data.cityDetail} onChange={(event) => update("cityDetail", event.target.value)} placeholder="مثال: حي النزهة، جدة" /></label></>}{step === 2 && <><label>اختر الخدمة إن أردت<select value={data.service} onChange={(event) => update("service", event.target.value)}><option value="">اختر الخدمة</option><option>تنظيف المنازل</option><option>الصيانة المنزلية</option><option>نقل العفش</option></select></label><label>أو اكتب نوع الخدمة بنفسك<input value={data.serviceDetail} onChange={(event) => update("serviceDetail", event.target.value)} placeholder="مثال: تنظيف شقة بعد انتقال" /></label></>}{step === 3 && <><div className="form-split"><label>التاريخ<input type="date" value={data.date} onChange={(event) => update("date", event.target.value)} /></label><label>الوقت<input type="time" value={data.time} onChange={(event) => update("time", event.target.value)} /></label></div><label>أي تفاصيل تهمك؟<textarea value={data.details} onChange={(event) => update("details", event.target.value)} maxLength={700} placeholder="اكتب أي تفاصيل إضافية، أو اترك الحقل فارغًا." /></label></>}{step === 4 && <label>رقم التواصل<input inputMode="tel" value={data.phone} onChange={(event) => update("phone", event.target.value)} placeholder="05xxxxxxxx" /><small>سيفتح واتساب برسالة جاهزة لتأكيد التفاصيل.</small></label>}<div className="booking-actions">{step > 1 && <button type="button" className="button button-ghost" onClick={() => setStep((current) => current - 1)}>السابق</button>}{step < 4 ? <button type="button" className="button" onClick={() => setStep((current) => current + 1)}>التالي <ArrowLeft size={16} /></button> : <button className="button" type="submit">إرسال عبر واتساب <MessageCircle size={16} /></button>}</div></form></div>;
}

export default function Home() {
  return <SiteShell><main dir="rtl">
    <section className="hero-section" id="top"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><i /> عناية تُرى، وراحة تُحس</span><h1>بيتك أنظف.<br /><em>يومك أخف.</em></h1><p>نمنح مساحتك عناية تستحقها، بخدمات تنظيف وصيانة ونقل عفش موثوقة تصل إليك في الوقت الذي يناسبك.</p><div className="hero-actions"><Link href="/booking" className="button">ابدأ الحجز <ArrowLeft size={17} /></Link><a href="tel:0509614797" className="text-link"><Phone size={16} /> تواصل معنا</a></div><div className="hero-stats"><span><strong>+12</strong> مدينة</span><span><strong>24/7</strong> دعم</span><span><strong>3</strong> مسارات عناية</span></div></div><div className="hero-art hero-caddy-art"><div className="hero-orbit" /><img src={assets.hero} alt="رسم شفاف لصندوق أدوات تنظيف الإشراقة" /><span className="art-note"><Sparkles size={16} /> تفاصيل صغيرة<br /><b>تصنع فرقًا كبيرًا</b></span></div></div><div className="wave-divider" /></section>
    <section className="section section-paper" id="services"><div className="shell"><div className="section-heading"><div><span className="eyebrow">خدماتنا</span><h2>نرتّب التفاصيل بهدوء،<br /><em>لتعود إلى يومك بخفة.</em></h2></div><p>خدمات عملية للأماكن التي نعيش ونعمل فيها. اختر المسار الأقرب لاحتياجك، وسنساعدك على ترتيب الخطوة التالية.</p></div><div className="service-grid">{services.map(({ icon: Icon, image, number, title, text }) => <article className="service-card" key={title}><span className="service-number">{number}</span><img className="service-art" src={image} alt="" draggable={false} /><Icon size={28} /><h3>{title}</h3><p>{text}</p><Link href="/services" className="card-link">استكشف التفاصيل <ArrowLeft size={15} /></Link></article>)}</div></div></section>
    <section className="section service-showcase"><div className="shell"><ServiceVideo featured title="تنظيف يراعي تفاصيل يومك" description="لقطة سريعة من روح الخدمة: عناية هادئة بالمكان، وترتيب واضح للأولويات قبل أن يبدأ اليوم من جديد." src="/manus-storage/ad-home-cleaning_8b448cef.mp4" /></div></section>
    <section className="section split-section" id="why"><div className="shell split-grid"><div className="service-illustration" aria-hidden="true"><div className="service-illustration-halo" /><img src={assets.maintenance} alt="" /></div><div className="split-copy"><span className="eyebrow">لماذا الإشراقة؟</span><h2>خدمة واضحة،<br /><em>وفريق يعرف ماذا يفعل.</em></h2><p>نبدأ من التفاصيل التي تهمك: نوع المكان، الأولوية، الوقت، وطريقة التواصل. ثم ننسّق ما يلزم دون وعود مبالغ فيها أو خطوات معقدة.</p><div className="check-list"><span><Check size={17} /> تحديد الأولويات قبل الوصول</span><span><Check size={17} /> مواد وتجهيزات تناسب الخدمة</span><span><Check size={17} /> تواصل مباشر لتأكيد الموعد</span></div><Link href="/about" className="text-link">اعرف أكثر عن طريقتنا <ArrowLeft size={16} /></Link></div></div></section>
    <section className="section coverage-section" id="coverage"><div className="shell coverage-grid"><div><span className="eyebrow">مدن ومناطق نصل إليها</span><h2>التغطية تبدأ<br /><em>برسالة واضحة.</em></h2><p>نصل إلى أكثر من 12 مدينة، وننسق معك قبل تثبيت الموعد. إذا لم تجد مدينتك، اكتبها داخل نموذج الحجز وسيتواصل معك الفريق.</p><div className="city-pills">{cities.map((city) => <span key={city}>{city}</span>)}</div><Link href="/where-we-work" className="button button-ghost">شاهد نطاق الخدمة <ArrowLeft size={16} /></Link></div><div className="map-panel"><img src={assets.map} alt="خريطة مدن تغطية شركة الإشراقة في السعودية" /></div></div></section>
    <section className="section process-section"><div className="shell"><div className="section-heading centered"><div><span className="eyebrow">كيف تسير الخدمة؟</span><h2>ثلاث خطوات، بلا تعقيد.</h2></div><p>نترك لك الوضوح من أول رسالة حتى نهاية الزيارة.</p></div><div className="process-grid"><div><span>01</span><Clock3 /><h3>حدد احتياجك</h3><p>اختر الخدمة والمدينة والموعد المناسب.</p></div><div><span>02</span><ShieldCheck /><h3>نصل في موعدنا</h3><p>فريق مدرّب يصل بالمعدات المناسبة.</p></div><div><span>03</span><Droplets /><h3>استمتع بالفرق</h3><p>مكان أهدأ، أنظف، وأقرب لما تحب.</p></div></div></div></section>
    <section className="section booking-section"><div className="shell"><BookingCard /></div></section>
    <section className="section article-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">من دليل العناية</span><h2>ملاحظات صغيرة<br /><em>تجعل المكان ألطف.</em></h2></div><Link href="/articles" className="text-link">كل المقالات <ArrowLeft size={16} /></Link></div><div className="article-grid"><Link href="/articles" className="article-card"><span>01 / الرياض</span><h3>تنظيف المنزل في الرياض: من أين تبدأ؟</h3><p>خريطة بسيطة لترتيب الأولويات قبل طلب الخدمة.</p></Link><Link href="/articles" className="article-card accent"><span>02 / جدة</span><h3>كيف تحافظ على خفة المكان بعد التنظيف؟</h3><p>عادات قصيرة تساعد على بقاء أثر العناية.</p></Link><Link href="/articles" className="article-card"><span>03 / مكة</span><h3>اختيار خدمة مناسبة للمساحة</h3><p>أسئلة عملية تجعل تنسيق الموعد أسرع.</p></Link></div></div></section>
    <VisitorFeedback />
    <section className="final-cta"><div className="shell final-cta-inner"><div><span className="eyebrow">نقاء يومك</span><h2>جاهز ترتّب الخطوة الأولى؟</h2><p>أرسل تفاصيل بسيطة، وسنساعدك على اختيار المسار المناسب.</p></div><Link href="/booking" className="button button-light">ابدأ الحجز <ArrowLeft size={17} /></Link></div></section>
  </main></SiteShell>;
}
