// Design reminder: calm editorial service brand; inner pages use readable measure, warm ivory, and deep teal signposts.
import { ArrowLeft, Check, MessageCircle, ShieldCheck, Sparkles, Truck, Wrench, Home as HomeIcon } from "lucide-react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";

const serviceRows = [[HomeIcon, "تنظيف المنازل", "تنظيف دوري أو عميق للمنازل والشقق، مع ترتيب الأولويات من المطبخ حتى المساحات التي تستقبل يومك."], [Wrench, "الصيانة المنزلية", "تنسيق أعمال الصيانة الأساسية بشرح واضح لما يحتاجه المكان، من التكييف إلى التفاصيل التي لا تحتمل التأجيل."], [Truck, "نقل العفش", "تجهيز وتغليف وتحميل الأثاث بعناية، مع قراءة حجم المكان وطبيعة القطع قبل أن تبدأ الرحلة."]];
function InnerHero({ label, title, text }: { label: string; title: string; text: string }) { return <section className="inner-hero"><div className="shell inner-hero-grid"><div><span className="eyebrow"><i /> {label}</span><h1>{title}</h1><p>{text}</p></div><div className="inner-hero-mark"><span>نقاء<br />يومك</span><b>01</b></div></div><div className="inner-wave" /></section>; }

export function ServicesPage() { return <SiteShell><main dir="rtl"><InnerHero label="الخدمات" title="ثلاثة مسارات للعناية اليومية." text="خدمات واضحة تبدأ من احتياجك الفعلي، وتتحول إلى موعد مرتب وخطوة يمكن متابعتها." /><section className="section section-paper"><div className="shell inner-service-grid">{serviceRows.map(([Icon, title, text], index) => { const ServiceIcon = Icon as typeof HomeIcon; return <article className="inner-service-card" key={title as string}><span>0{index + 1}</span><ServiceIcon size={31} /><h2>{title as string}</h2><p>{text as string}</p><div className="check-list"><span><Check size={16} /> تواصل مباشر</span><span><Check size={16} /> موعد منسق</span><span><Check size={16} /> تفاصيل قبل البدء</span></div><Link href="/booking" className="button button-ghost">اطلب هذه الخدمة <ArrowLeft size={16} /></Link></article>; })}</div></section></main></SiteShell>; }

export function BookingPage() { return <SiteShell><main dir="rtl"><InnerHero label="الحجز" title="خلّ التفاصيل الأولى بسيطة." text="اكتب المدينة والخدمة والوقت المناسب، وسيفتح لك الموقع رسالة واتساب جاهزة للمراجعة والإرسال." /><section className="section booking-section"><div className="shell"><div className="booking-card booking-page-card"><div className="booking-intro"><span className="eyebrow">نموذج الحجز</span><h2>احجز من الصفحة الرئيسية</h2><p>النموذج المختصر موجود في الصفحة الرئيسية ليبقى السياق قريبًا منك.</p><Link href="/#booking" className="button">انتقل إلى النموذج <ArrowLeft size={16} /></Link></div><div className="booking-side-note"><MessageCircle size={30} /><h3>واتساب هو الخطوة التالية</h3><p>لا يتم حفظ البيانات في هذه النسخة الاحتياطية؛ عند الإرسال تنتقل الرسالة إلى رقم التواصل فقط.</p><a href="https://wa.me/966552610151" className="text-link" target="_blank" rel="noreferrer">فتح واتساب <ArrowLeft size={16} /></a></div></div></div></section></main></SiteShell>; }

export function ArticlesPage() { const articles = [["تنظيف الرياض: خطوات البداية", "كيف تقرأ المساحة قبل أن تطلب الخدمة، وما الذي يستحق أن يكون في أول رسالة."], ["العناية بالمطبخ دون إرهاق", "تقسيم صغير للمهام يجعل لمعان الأسطح عادة خفيفة بدل قائمة طويلة."], ["متى تحتاج إلى صيانة التكييف؟", "إشارات مبكرة تساعدك على ترتيب الفحص قبل أن يتحول الحر إلى مفاجأة."], ["نقل العفش بهدوء من باب إلى باب", "أسئلة التغليف والممرات والموعد التي تختصر الكثير من الارتباك يوم النقل."], ["تنظيف جدة في الأجواء الرطبة", "أفكار بسيطة للتعامل مع أثر الرطوبة والمحافظة على إحساس الهواء النظيف."], ["ترتيب موعد الخدمة في مكة", "كيف تكتب التفاصيل المهمة من البداية لتصل إلى تنسيق أسهل وموعد أوضح."]]; return <SiteShell><main dir="rtl"><InnerHero label="دليل العناية" title="مقالات قصيرة عن المكان الذي تعيش فيه." text="محتوى إرشادي مستعاد من بنية الموقع السابقة، بصياغة عملية تساعدك على ترتيب الاحتياج قبل التواصل." /><section className="section section-paper"><div className="shell article-list">{articles.map(([title, text], index) => <article key={title}><span>مقال {String(index + 1).padStart(2, "0")}</span><h2>{title}</h2><p>{text}</p><a href="mailto:hello@ishraqa.sa?subject=استفسار عن المقال" className="text-link">اسأل عن التفاصيل <ArrowLeft size={15} /></a></article>)}</div></section></main></SiteShell>; }

export function CoveragePage() { return <SiteShell><main dir="rtl"><InnerHero label="نطاق الخدمة" title="نصل إلى مدن كثيرة، ونبدأ من عنوان واضح." text="التغطية ليست قائمة جامدة؛ اكتب موقعك وسيتأكد الفريق من إمكانية تنسيق الخدمة قبل تثبيت الموعد." /><section className="section section-paper"><div className="shell coverage-detail"><div><h2>المدن الأساسية</h2><div className="city-pills large">{["الرياض", "جدة", "مكة المكرمة", "المدينة المنورة", "الدمام", "الخبر", "الطائف", "أبها", "تبوك", "القصيم", "جازان", "نجران", "حائل", "الأحساء"].map((city) => <span key={city}>{city}</span>)}</div></div><div className="coverage-callout"><Sparkles size={27} /><h3>لا تجد مدينتك؟</h3><p>اختر «مدن أخرى» في نموذج الحجز، واكتب اسم مدينتك في رسالة واتساب.</p><Link href="/booking" className="button">اكتب مدينتك <ArrowLeft size={16} /></Link></div></div></section></main></SiteShell>; }

export function AboutPage() { return <SiteShell><main dir="rtl"><InnerHero label="عن الإشراقة" title="العناية لا تحتاج ضجيجًا." text="نحن نبني تجربة خدمة قريبة: تفاصيل كافية، تنسيق واضح، واهتمام بما يجعل يومك أسهل." /><section className="section section-paper"><div className="shell about-grid"><div><span className="eyebrow">طريقتنا</span><h2>نبدأ من احتياجك، لا من قائمة جاهزة.</h2><p>كل مكان له إيقاعه. لذلك نسأل عن نوع الخدمة، طبيعة المساحة، الموعد، وأي نقطة تحتاج عناية خاصة. بعدها نرتب الخطوة التالية بلغة مفهومة.</p><div className="check-list"><span><ShieldCheck size={17} /> وضوح قبل التنفيذ</span><span><Check size={17} /> احترام وقتك ومساحتك</span><span><Sparkles size={17} /> عناية تظهر في التفاصيل</span></div></div><div className="quote-card"><p>«نرتّب التفاصيل بهدوء، لتعود أنت إلى يومك بخفة.»</p><small>صوت الإشراقة</small></div></div></section></main></SiteShell>; }

export function FaqPage() { const faqs = [["هل يمكن الحجز عبر واتساب؟", "نعم، النموذج يجهز رسالة واضحة تراجعها ثم ترسلها إلى رقم التواصل."], ["هل تغطون مدينتي؟", "نغطي مدنًا متعددة، ويمكنك اختيار «مدن أخرى» وكتابة مدينتك للتأكد قبل الموعد."], ["هل يتم الدفع عبر الموقع؟", "لا. هذه النسخة الاحتياطية لا تنفذ دفعًا إلكترونيًا، ويؤكد الفريق التفاصيل معك مباشرة."], ["كيف أعرف الخدمة الأنسب؟", "أرسل وصفًا بسيطًا للمكان والنتيجة التي تريدها، وسيساعدك فريق التواصل على تحديد المسار الأقرب."]]; return <SiteShell><main dir="rtl"><InnerHero label="الأسئلة الشائعة" title="إجابات قصيرة قبل أن تبدأ." text="إذا لم تجد إجابتك، تواصل معنا مباشرة وسنوضح لك الخطوة التالية." /><section className="section section-paper"><div className="shell faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section></main></SiteShell>; }
